spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.change-master.xml
  mail:
    host: localhost
    port: 1025
    username: user
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
application:
  security:
    jwt:
      secret-key: ${JWT-SECRET-KEY}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: http://localhost:3000/activate-account
  file:
    uploads:
      photos-output-path: ./uploads
server:
  port: 8088

mybatis:
  type-aliases-package: "com.lifecraft.todoappspringbootsrv.domain"
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.lifecraft.todoappspringbootsrv.typehandler